"""Add telegram_id field for User, read for Message

Revision ID: 50531443bc48
Revises: bb0ba64f0db4
Create Date: 2024-11-13 17:51:45.548977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50531443bc48'
down_revision: Union[str, None] = 'bb0ba64f0db4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('read', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('telegram_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'telegram_id')
    op.drop_column('messages', 'read')
    # ### end Alembic commands ###
